on:
  push:
    tags:
    - "v*"

env:
    GH_TOKEN: ${{ github.token }}

name: Release
permissions:
    contents: write
    id-token: write
jobs:
  release-cross-arch:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Cross Arch Build
      run: |
        make ci
      env:
        CROSS: "true"

    - name: release binaries
      run: |
        gh release upload ${{ github.ref_name }} dist/artifacts/*
        